---
python:
  - "2.7"
# - "3.6"
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible==2.5.0
  - pip install molecule
  - pip install docker-py
script:
  - molecule --version
  - ansible --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
