---
- name: reload daemons
  systemd:
    daemon_reload: yes

- name: restart ansible
  service:
    name: sshd_ansible
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
...
