---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: centos:7
    privileged: true
  - name: ubuntu
    image: ubuntu:bionic
    privileged: true
  - name: debian
    image: debian:stretch
    privileged: true
verifier:
  name: testinfra
